fallback when run from Node interpreter.
This bug was introduced with 9ea9385. Since Node interpreter don't
have `process.argv[1]`, `path.dirname` would fail with the following
error:

    TypeError: Path must be a string. Received undefined

See: #158.